version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"

sphinx:
  configuration: docs/config/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .